### PR TITLE
Add LinkCustomizationName to CreateLinkTokenRequest

### PR DESCRIPTION
**Pull request by jbmitchell**
Add LinkCustomizationName to CreateLinkTokenRequest 

https://plaid.com/docs/api/tokens/#link-token-create-request-link-customization-name

### CODE REVIEW

**Comment by viceroypenguin** [comment]
Could you also add the `android_package_name` field? Thanks!

**Comment by jbmitchell** [comment]
> Could you also add the `android_package_name` field? Thanks!

6916cba3bd11fb01e22f3d4cc3c22e9c962be5f0

**Comment by viceroypenguin** [comment]
Thanks!

**Comment by viceroypenguin** [comment]
Released via v2.6.0

**Pull request merged**
